### ISSUE TITLE
Blank screen when running ("returning nil because device is nil")

### ISSUE THREAD

**Issue by sy2002** [haroldserrano/GettingStartedWithMetal#1]
@haroldserrano: Thank you for sharing so much information about game engine programming including the tutorials you made. This is very valuable!

I just started to follow your course https://www.haroldserrano.com/blog/getting-started-with-metal-api and there, a link brought me to this repo. Interesstingly enough, it brought me to a branch within the repo called MetalBasics. I used the ZIP downloader, unzipped and opened the XCode project. I am on macOS 10.14 with XCode 11.3.1.

I then went to the Scheme and deactivated ""Metal API validation" as I saw this in one of your videos about installing the Untoldengine. After compiling and running for the target for the iPhone 11 Pro (simulator, no real device), this is the error messages I get, i.e. it does not work, there is a blank screen:

```
2020-02-08 09:05:48.990969+0100 GettingStartedMetal[8193:4425166] [CAMetalLayer nextDrawable] returning nil because device is nil.
2020-02-08 09:05:48.997626+0100 GettingStartedMetal[8193:4425166] [CAMetalLayer nextDrawable] returning nil because device is nil.
2020-02-08 09:05:49.011861+0100 GettingStartedMetal[8193:4425166] [CAMetalLayer nextDrawable] returning nil because device is nil.`

[... it goes on like this ...]
```

P.S.: Unrelated to the error, but do I need to do this in the iOS emulator or can I just run the sample as a macOS app?

**Comment by untoldengine** [comment]
Hi @sy2002, metal is not supported on the simulator. You need to connect a real device. 
BTW, I tested the project with the latest Xcode 11.3 and the project works.

P.S. I didn't set up the project to work with macOS, only for iOS. The project only renders a simple square. Nothing fancy at all, no shading, no nothing. The main point of the article was to explain how metal works. Thanks

**Comment by sy2002** [comment]
@untoldengine  Thank you very much for your fast feedback. I was not aware, that the simulator is not supporting metal. I will use a real device to work through your article.
